### ISSUE TITLE
Add MX4SIO support

### ISSUE THREAD

**Issue by camilitox** [israpps/PlayStation2-Basic-BootLoader#15]
is possible to add support for booting applications from mx4sio?

**Comment by israpps** [comment]
> is possible to add support for booting applications from mx4sio?

Hi!

Yes! it is possible!

It will be a kinda annoying implementation because BDM maps MX4SIO devices as if they were USB (`mass#:/`)

But i can surely do it!

**Comment by israpps** [comment]
already done

**Comment by israpps** [comment]
[PS2BBL_MX4SIO.zip](https://github.com/israpps/PlayStation2-Basic-BootLoader/files/12030836/PS2BBL_MX4SIO.zip)
Could you test if it works?

MX4SIO apps must be accessed by using the device `massX:` (case sensitive)

for example:
```
massX:/APPS/BOOT.ELF
```
