### ISSUE TITLE
PS2BBL X MX4SIO compatibility [FR]: 

### ISSUE THREAD

**Issue by Helxgamer** [israpps/PlayStation2-Basic-BootLoader#29]
### other checks

- [X] I've checked if such feature exists on [Latest version](https://github.com/israpps/PlayStation2-Basic-BootLoader/releases/)
- [ ] This Feature requires an update of [PS2SDK](https://github.com/ps2dev/ps2sdk)

### Explanation

hello everything is fine ?

I wanted to ask how I configure the PS2BBL to boot the OPL inside the MX4SIO and if the minor card is not connected, it should boot the MC0 normally.

I configured it as follows.
LK_AUTO_E1 = massX:/APPS/OPNPS2LD.ELF
LK_AUTO_E2 = mc?:/APPS/OPNPS2LD.ELF
LK_AUTO_E3 = mc?:/OPL/OPNPS2LD.ELF

however I use kelfblinder and it seems to me that the PS2 BBL version of it is not compatible To boot the MX4SIO, how do I install the version that has this function together with kelfblinder?.

**Comment by israpps** [comment]
binaries for PS2BBL system update with MX4SIO support can be found on the [kelf release tag](https://github.com/israpps/PlayStation2-Basic-BootLoader/releases/tag/kelf)

replace the appropiate `SYSTEM.XLF` file on KELFBinder `INSTALL/KELF` directory and install again. if you wanna avoid wiping already stored config files and so on, please press __L1__  while on KELFBinder main menu, a yellow notification saying `extra files will not be installed` will appear on screen, indicating youre good to go for just replacing the update

**Comment by Helxgamer** [comment]
You are amazing comrade, thank you very much.
Hugs and all the best to you
