### ISSUE TITLE
[ISSUE]: massX:/ MX4SIO não está dando BOOT com o PS2BBL

### ISSUE THREAD

**Issue by LilMatrix** [israpps/PlayStation2-Basic-BootLoader#46]
### Checks

- [ ] I have checked [__existing issues__](https://github.com/israpps/PlayStation2-Basic-BootLoader/issues) for duplicates and found none
- [X] I am using a build downloaded from [this repository](https://github.com/israpps/PlayStation2-Basic-BootLoader/releases)

### Describe the issue

Não consegui dar BOOT, dá forma que foi informado como deveria ser para funcionar, posso ter entendido errado, e ser a dúvida de outros também. O arquivo PS2BBL.ELF na pasta BOOT em mc0, bom tentei com os arquivos no memory card e no pendrive, como OPL e wLaunch, porque não rolou no MX4SIO, e fugiria do propósito de economizar espaço no MemoryCard, mesmo assim não funcionou, com o CONFIG.INI em AUTO: massX:/ .... o que poderia ser ?
 A pasta PS2BBL estava no MX4SIO, e OPL e o Launch.ELF estão na pasta BOOT do MX4SIO, estão está parecendo tudo certo. ?

### Console model

Unidade SCPH-90001

### Program version (if possible, also provide hash)

PlayStation Driver 2.00

### System modifications

Modchip

### What kind of boot method are you using to run the bootloader?

DEV1 / DEV2 / INFMAN

### Context and extra information

Matrix 1.93 que salva as configurações.

**Comment by LilMatrix** [comment]
Bom quero dizer que eu consegui, a solução foi a seguinte: O vídeo do HardLevel é antigo então peguei os arquivos para download antigo, quero dizer que o PS2BBL 1.2.0 funcionou o mais recente, o antigo não estava dando boot, congelava com um pontinho em cima e não carregava, creio que já com o Installer+Opentuna 1.2.0 deve funcionar também, mas deverá atualizar o CONFIG.INI para configurar o caminho do MX4SIO massX, Obrigado Matias, e esclarecendo para futuros, alguém que não estiver conseguindo é isso, as versões mais recentes 1.2.0 funciona, o principal é o BOOT do PS2BBL, se passar carrega normalmente o boot do MX4SIO, VLW galeraa!

**Comment by israpps** [comment]
whatever the problem is, it comes from PS2SDK. PS2BBL codebase has not been updated since 5 months.

Not to mention that the final executable size went from `83` to `97` kb.

Will take a closer look to this problems next week or so

**Comment by LilMatrix** [comment]
Bom, Matias o importante é que o novo release atualizado funciona as versões 1.2.0, no SCPH-90001 . ..

**Comment by LeandroFerreira445** [comment]
Agora está funcionando perfeitamente obrigado @fjtrujy @israpps

**Comment by israpps** [comment]
fixed on #50
