### ISSUE TITLE
[FR]: Leitura do POPSTARTER com o MX4SIO,

### ISSUE THREAD

**Issue by LilMatrix** [israpps/PlayStation2-Basic-BootLoader#47]
### other checks

- [X] I've checked if such feature exists on [Latest version](https://github.com/israpps/PlayStation2-Basic-BootLoader/releases/)
- [ ] This Feature requires an update of [PS2SDK](https://github.com/ps2dev/ps2sdk)

### Explanation

Could you add... não só também a leitura de mass, mas também ter um massX ai, seria uma boa, e também é esperado seria uma surpresa e novidade, para todos da CENA, com o seu POPSLOADER, é uma boa pedida, EL ISRA! é o que eu proponho.
Abriria as portas de novas possibilidades, inovação e criatividade, admiro seu trabalho.

**Comment by israpps** [comment]
1. POPStarter can't work with MX4SIO
2. This is the PS2BBL repository, your request is out of topic here.

**Comment by LilMatrix** [comment]
Entende, verdade, ok, está certo, ABÇS. E me desculpe, passei dos limites do tópico, não percebi!
