### ISSUE TITLE
[ISSUE]: unable to load CONFIG.INI from memory card

### ISSUE THREAD

**Issue by smeegle5000** [israpps/PlayStation2-Basic-BootLoader#55]
### Checks

- [X] I have checked [__existing issues__](https://github.com/israpps/PlayStation2-Basic-BootLoader/issues) for duplicates and found none
- [X] I am using a build downloaded from [this repository](https://github.com/israpps/PlayStation2-Basic-BootLoader/releases)

### Describe the issue

i have been able to successfully load the CONFIG.INI i have created from a usb drive (4gb fat32) in the directory:
`./PS2BBL/CONFIG.INI`

i have not been able to have the console load the same CONFIG.INI from a memory card (both mentioned being official sony cards) by attempting to put it in the directories:

card bbl is installed on (have tried slot 1 and 2):
```
./SYS-CONF/CONFIG.INI
./PS2BBL/CONFIG.INI
./CONFIG.INI
```

a second blank card in the other slot along with the one bbl is installed on:
```
./SYS-CONF/CONFIG.INI
./PS2BBL/CONFIG.INI
./CONFIG.INI
```

i cant seem to see anything i may be doing wrong?

### Console model

SCPH 790002

### Program version (if possible, also provide hash)

v1.2.0 commit f42daec

### What kind of boot method are you using to run the bootloader?

System Update

**Comment by israpps** [comment]
PS2BBL has changed the location of the config files for simplicity on it's last update

now the memory card config is located at:
```
mc?:/SYS-CONF/PS2BBL.INI
```

**Comment by smeegle5000** [comment]
ah, works perfectly now, thank you, the github.io configuration page may need updating with this information, thanks :)
